version: "3.9"

services:
  discord-bot:
    build: ./discord
    env_file:
      - main.env
      - discord.env
    depends_on:
      - nats

  manager:
    build: ./manager
    env_file:
      - main.env
    depends_on:
      - nats
    volumes:
      - images:/app/images

  teamspeak:
    image: teamspeak
    restart: always
    ports:
      - "9987:9987/udp"
      - "30033:30033"
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: db
      TS3SERVER_DB_USER: root
      TS3SERVER_DB_PASSWORD: 
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      # this doesnt matter, the db isnt connected to the internet
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: teamspeak
    volumes:
      - teamspeakdb:/var/lib/mysql

  nats:
    image: nats

  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      # source folder can be moved elsewhere
      - /home/Bleifish/xxx/src:/var/www/html

  php-fpm:
    build: ./website
    volumes:
      - /home/Bleifish/xxx/src:/var/www/html
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on: 
      - db
    environment:
      PMA_HOST: db
      MYSQL_PASSWORD: 
      PMA_ABSOLUTE_URI: https://php.phx.ziv.shalit.name/
      PMA_USER: dbadmin
      PMA_PASSWORD: 

volumes:
  caddy_data:
    name: phoenixbot_caddy_data
    external: true
  caddy_config:

  teamspeakdb:
    name: phoenixbot_teamspeakdb
    external: true

  images:
    name: phoenixbot_images
    external: true

#networks:
#  db-network:
#    driver: bridge
#    internal: true
#  internal:
#    driver: bridge
