version: "3.9"

services:
  discord-bot:
    build: ./discord
    env_file:
      - main.env
      - discord.env
    depends_on:
      - nats

  manager:
    build: ./manager
    env_file:
      - main.env
    depends_on:
      - nats

  teamspeak:
    image: teamspeak
    restart: always
    ports:
      - "9987:9987/udp"
      - "30033:30033"
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: db
      TS3SERVER_DB_USER: root
      TS3SERVER_DB_PASSWORD: teamspeakDBPassword
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      # this doesnt matter, the db isnt connected to the internet
      MYSQL_ROOT_PASSWORD: teamspeakDBPassword
      MYSQL_DATABASE: teamspeak
    volumes:
      - teamspeakdb:/var/lib/mysql

  nats:
    image: nats

  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "8080:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      # source folder can be moved elsewhere
      - ../xxx/src:/var/www/html

  php-fpm:
    image: php:8.1-fpm
    volumes:
      - ../xxx/src:/var/www/html

volumes:
  caddy_data:
    name: phoenixbot_caddy_data
    external: true
  caddy_config:

  teamspeakdb:
    name: phoenixbot_teamspeakdb
    external: true

#networks:
#  db-network:
#    driver: bridge
#    internal: true
#  internal:
#    driver: bridge
