version: "3.9"

services:
  discord-bot:
    build: ./discord
    env_file:
      - main.env
      - discord.env
    depends_on:
      - nats

  manager:
    build: ./manager
    env_file:
      - main.env
    ports:
      - "8080:8080"
    depends_on:
      - nats

  nats:
    image: nats
    ports:
      - "8222:8222"

networks:
  internet:
    driver: bridge
  ts-net:
    external: true
    name: "teamspeak-connection"
