version: '3.9'
services:
  teamspeak:
    image: teamspeak
    restart: always
    ports:
      - "9987:9987/udp"
      - "30033:30033"
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: db
      TS3SERVER_DB_USER: root
      TS3SERVER_DB_PASSWORD: teamspeakDBPassword
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
    depends_on:
      - db
    networks:
      - no-internet
      - internet
      - ts-net
  db:
    image: mariadb
    restart: always
    environment:
      # this doesnt matter, the db isnt connected to the internet
      MYSQL_ROOT_PASSWORD: teamspeakDBPassword
      MYSQL_DATABASE: teamspeak
    networks:
      - no-internet
    volumes:
      - teamspeakdb:/var/lib/mysql

volumes:
  teamspeakdb:

networks:
  no-internet:
    driver: bridge
    internal: true
  internet:
    driver: bridge
  ts-net:
    driver: bridge
    name: "teamspeak-connection"