version: "3.9"

services:
  discord-bot:
    build: ./discord
    env_file:
      - main.env
      - discord.env
    depends_on:
      - nats

  manager:
    build: ./manager
    env_file:
      - main.env
#    ports:
#      - "8080:8080"
    depends_on:
      - nats

  nats:
    image: nats
#    ports:
#      - "8222:8222"

  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
    external: true
  caddy_config:

networks:
  internet:
    driver: bridge
  ts-net:
    external: true
    name: "teamspeak-connection"
